CREATE DATABASE IF NOT EXISTS `UDV.Product.Core`;
USE `UDV.Product.Core`;

DROP USER IF EXISTS 'sa'@'%';
CREATE USER 'sa'@'%' IDENTIFIED WITH mysql_native_password BY 'Password!234';
GRANT ALL PRIVILEGES ON `UDV.Product.Core`.* TO 'sa'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `RoleData` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Description` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO `RoleData` (`Id`, `Description`)
VALUES 
  (1, 'Administrator'),
  (2, 'User');

CREATE TABLE IF NOT EXISTS `UserData` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `DisplayName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL UNIQUE,
  `Role` INT NOT NULL DEFAULT 2,
  `Password` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `LockedDate` DATETIME NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `ProductData` (
  `Id` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `Name` VARCHAR(100) NOT NULL UNIQUE,
  `Description` TEXT,
  `UnitPrice` DECIMAL(12,2) NOT NULL,
  `Stock` INT NOT NULL,
  `IsAvailable` BOOLEAN DEFAULT TRUE,
  `Sku` VARCHAR(50),
  `Category` VARCHAR(50),
  `Status` ENUM('active', 'inactive', 'discontinued') DEFAULT 'active',
  `Attributes` JSON,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DeletedAt` TIMESTAMP NULL DEFAULT NULL
);
