CREATE DATABASE IF NOT EXISTS `UDV.Product.Core`;
USE `UDV.Product.Core`;

DROP USER IF EXISTS 'sa'@'%';
CREATE USER 'sa'@'%' IDENTIFIED WITH mysql_native_password BY 'Password!234';
GRANT ALL PRIVILEGES ON `UDV.Product.Core`.* TO 'sa'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `RoleData` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Description` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO `RoleData` (`Id`, `Description`)
VALUES 
  (1, 'Administrator'),
  (2, 'User');

CREATE TABLE IF NOT EXISTS `UserData` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `DisplayName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL UNIQUE,
  `Role` INT NOT NULL DEFAULT 2,
  `Password` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `LockedDate` DATETIME NULL DEFAULT NULL
);
